### ISSUE TITLE
Costs in API does include decimals for Euros and can't be mapped to Int

### ISSUE THREAD

**Issue by larsdunemark** [glesys/glesys-go#35]
Current solution expects all costs to be mapped to an Int, if a organization use Euros instead of SEK and IPv6 address will end up with a cost of 0.1 Euro and will fail to parse the json.

https://github.com/glesys/glesys-go/search?q=Amount+int+json%3Aamount

**Comment by larsdunemark** [comment]
Also cost in Loadbalancers is incorrect mapped. https://github.com/glesys/glesys-go/blob/master/loadbalancers.go#L34

**Comment by norrland** [comment]
Fixed with #42
