### ISSUE TITLE
Update to sane default params in Server

### ISSUE THREAD

**Issue by norrland** [glesys/glesys-go#61]
https://github.com/glesys/glesys-go/blob/3e76300562a325ecd8f9c4338fd8f8b0b42c4cf7/servers.go#L131

Related to #60

**Comment by brother** [comment]
Interesting indeed. This is a hard one.

For [GleShYS](https://github.com/brother/gleshys) I used a "dynamic default" where it would use the lowest allowed setting for the template+platform selected. A windown machine will always need more power than the linux boxes for instance. Maybe a very high default is a good start to avoid having unusable values.
